web:
  restart: always
  build: ./twoweeks
  expose:
    - "8000"
  #links:
  #  - postgres:postgres
  volumes:
    #- /usr/src/twoweeks/static
    - /twoweeks/static
  env_file: .env
  command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app


nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - web
  links:
    - web:twoweeks