############################################################
# Dockerfile to build 2weeks App
FROM python:2-onbuild

#Move files

#COPY ./ /usr/src/app

#WORKDIR app/

CMD [ "python", "./app.py" ]

#git clone https://github.com/Donovan80/App.git